// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"github.com/samber/do/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStrategy creates a new instance of MockStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStrategy {
	mock := &MockStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStrategy is an autogenerated mock type for the Strategy type
type MockStrategy struct {
	mock.Mock
}

type MockStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStrategy) EXPECT() *MockStrategy_Expecter {
	return &MockStrategy_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockStrategy
func (_mock *MockStrategy) Execute() (*StrategyResult, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *StrategyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*StrategyResult, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *StrategyResult); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StrategyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStrategy_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStrategy_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockStrategy_Expecter) Execute() *MockStrategy_Execute_Call {
	return &MockStrategy_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockStrategy_Execute_Call) Run(run func()) *MockStrategy_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStrategy_Execute_Call) Return(strategyResult *StrategyResult, err error) *MockStrategy_Execute_Call {
	_c.Call.Return(strategyResult, err)
	return _c
}

func (_c *MockStrategy_Execute_Call) RunAndReturn(run func() (*StrategyResult, error)) *MockStrategy_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// SetContainer provides a mock function for the type MockStrategy
func (_mock *MockStrategy) SetContainer(container do.Injector) {
	_mock.Called(container)
	return
}

// MockStrategy_SetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContainer'
type MockStrategy_SetContainer_Call struct {
	*mock.Call
}

// SetContainer is a helper method to define mock.On call
//   - container do.Injector
func (_e *MockStrategy_Expecter) SetContainer(container interface{}) *MockStrategy_SetContainer_Call {
	return &MockStrategy_SetContainer_Call{Call: _e.mock.On("SetContainer", container)}
}

func (_c *MockStrategy_SetContainer_Call) Run(run func(container do.Injector)) *MockStrategy_SetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 do.Injector
		if args[0] != nil {
			arg0 = args[0].(do.Injector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStrategy_SetContainer_Call) Return() *MockStrategy_SetContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStrategy_SetContainer_Call) RunAndReturn(run func(container do.Injector)) *MockStrategy_SetContainer_Call {
	_c.Run(run)
	return _c
}

// Support provides a mock function for the type MockStrategy
func (_mock *MockStrategy) Support(probe StrategyType) bool {
	ret := _mock.Called(probe)

	if len(ret) == 0 {
		panic("no return value specified for Support")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(StrategyType) bool); ok {
		r0 = returnFunc(probe)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStrategy_Support_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Support'
type MockStrategy_Support_Call struct {
	*mock.Call
}

// Support is a helper method to define mock.On call
//   - probe StrategyType
func (_e *MockStrategy_Expecter) Support(probe interface{}) *MockStrategy_Support_Call {
	return &MockStrategy_Support_Call{Call: _e.mock.On("Support", probe)}
}

func (_c *MockStrategy_Support_Call) Run(run func(probe StrategyType)) *MockStrategy_Support_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 StrategyType
		if args[0] != nil {
			arg0 = args[0].(StrategyType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStrategy_Support_Call) Return(b bool) *MockStrategy_Support_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStrategy_Support_Call) RunAndReturn(run func(probe StrategyType) bool) *MockStrategy_Support_Call {
	_c.Call.Return(run)
	return _c
}
