// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/Arheon/markus-backend/internal/server/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerRepository creates a new instance of MockServerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerRepository {
	mock := &MockServerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerRepository is an autogenerated mock type for the ServerRepository type
type MockServerRepository struct {
	mock.Mock
}

type MockServerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerRepository) EXPECT() *MockServerRepository_Expecter {
	return &MockServerRepository_Expecter{mock: &_m.Mock}
}

// CreateNewServer provides a mock function for the type MockServerRepository
func (_mock *MockServerRepository) CreateNewServer(ctx context.Context, userID string, serverName string) (*entity.Server, error) {
	ret := _mock.Called(ctx, userID, serverName)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewServer")
	}

	var r0 *entity.Server
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Server, error)); ok {
		return returnFunc(ctx, userID, serverName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Server); ok {
		r0 = returnFunc(ctx, userID, serverName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Server)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, serverName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerRepository_CreateNewServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewServer'
type MockServerRepository_CreateNewServer_Call struct {
	*mock.Call
}

// CreateNewServer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - serverName string
func (_e *MockServerRepository_Expecter) CreateNewServer(ctx interface{}, userID interface{}, serverName interface{}) *MockServerRepository_CreateNewServer_Call {
	return &MockServerRepository_CreateNewServer_Call{Call: _e.mock.On("CreateNewServer", ctx, userID, serverName)}
}

func (_c *MockServerRepository_CreateNewServer_Call) Run(run func(ctx context.Context, userID string, serverName string)) *MockServerRepository_CreateNewServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerRepository_CreateNewServer_Call) Return(server *entity.Server, err error) *MockServerRepository_CreateNewServer_Call {
	_c.Call.Return(server, err)
	return _c
}

func (_c *MockServerRepository_CreateNewServer_Call) RunAndReturn(run func(ctx context.Context, userID string, serverName string) (*entity.Server, error)) *MockServerRepository_CreateNewServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllServersByUserID provides a mock function for the type MockServerRepository
func (_mock *MockServerRepository) GetAllServersByUserID(ctx context.Context, userID string) ([]*entity.Server, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllServersByUserID")
	}

	var r0 []*entity.Server
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Server, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Server); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Server)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerRepository_GetAllServersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllServersByUserID'
type MockServerRepository_GetAllServersByUserID_Call struct {
	*mock.Call
}

// GetAllServersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockServerRepository_Expecter) GetAllServersByUserID(ctx interface{}, userID interface{}) *MockServerRepository_GetAllServersByUserID_Call {
	return &MockServerRepository_GetAllServersByUserID_Call{Call: _e.mock.On("GetAllServersByUserID", ctx, userID)}
}

func (_c *MockServerRepository_GetAllServersByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockServerRepository_GetAllServersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerRepository_GetAllServersByUserID_Call) Return(servers []*entity.Server, err error) *MockServerRepository_GetAllServersByUserID_Call {
	_c.Call.Return(servers, err)
	return _c
}

func (_c *MockServerRepository_GetAllServersByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Server, error)) *MockServerRepository_GetAllServersByUserID_Call {
	_c.Call.Return(run)
	return _c
}
