#####################################################
#                                                   #
#              Check on status of URLs              #
#                                                   #    
#####################################################
[[inputs.statsd]]
    protocol = "udp"
    service_address = ":8125"
    metric_separator = "_"

#####################################################
#                                                   #
#          Export Information to Prometheus         #
#                                                   #
#####################################################
[[outputs.prometheus_client]]
    listen = ":9101"
    expiration_interval = "60s"
