database:
  driver: postgres
  dsn: postgres://user:password@localhost:8884/markus_test?sslmode=disable&connect_timeout=1
server:
  port: :8025
auth:
  jwt_token_lookup: "header:Authorization,cookie:jwt"
  identity_key: "id"
