// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/Arheon/markus-backend/internal/user/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateNewUserOrErrorIfExists provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateNewUserOrErrorIfExists(context1 context.Context, username string, password string) (*entity.User, error) {
	ret := _mock.Called(context1, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUserOrErrorIfExists")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.User, error)); ok {
		return returnFunc(context1, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.User); ok {
		r0 = returnFunc(context1, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CreateNewUserOrErrorIfExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewUserOrErrorIfExists'
type MockUserRepository_CreateNewUserOrErrorIfExists_Call struct {
	*mock.Call
}

// CreateNewUserOrErrorIfExists is a helper method to define mock.On call
//   - context1 context.Context
//   - username string
//   - password string
func (_e *MockUserRepository_Expecter) CreateNewUserOrErrorIfExists(context1 interface{}, username interface{}, password interface{}) *MockUserRepository_CreateNewUserOrErrorIfExists_Call {
	return &MockUserRepository_CreateNewUserOrErrorIfExists_Call{Call: _e.mock.On("CreateNewUserOrErrorIfExists", context1, username, password)}
}

func (_c *MockUserRepository_CreateNewUserOrErrorIfExists_Call) Run(run func(context1 context.Context, username string, password string)) *MockUserRepository_CreateNewUserOrErrorIfExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateNewUserOrErrorIfExists_Call) Return(user *entity.User, err error) *MockUserRepository_CreateNewUserOrErrorIfExists_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_CreateNewUserOrErrorIfExists_Call) RunAndReturn(run func(context1 context.Context, username string, password string) (*entity.User, error)) *MockUserRepository_CreateNewUserOrErrorIfExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(context1 context.Context, userID string) (*entity.User, error) {
	ret := _mock.Called(context1, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(context1, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(context1, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - context1 context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetUserByID(context1 interface{}, userID interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", context1, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(context1 context.Context, userID string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user *entity.User, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(context1 context.Context, userID string) (*entity.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
